#!/usr/bin/env bash
#
# Copyright 2011, Tim Branyen @tbranyen <tim@tabdeveloper.com>
# Dual licensed under the MIT and GPL licenses.
#
# Script for fetching a package from AUR, optionally fetching all
# dependancies, removing a package and optionall all dependancies.
#

# Internal properties
SEARCH_PREFIX='http://aur.archlinux.org/packages.php?O=0&do_Search=Go&K='
RPC_URL='http://aur.archlinux.org/rpc.php'
ACTIONS='search install remove'

function main {
  # Missing arguments
  args=("$@")
  if [ $# -lt 1 ]; then
    echo '
      aur: try ''`aur --help`'' for more information
    '
    exit
  fi

  # Display help text
  if [ ${args[0]} = '--help' ]; then
    echo '
      Search for package:
        aur search package_name
      
      Install single package: (will warn if requires dependancies)
        aur install package_name

      Install single package and all dependancies:
        aur install package_name --all

      Remove single package: (keeping all dependancies)
        aur remove package_name

      Remove single package and all dependancies:
        aur remove package_name --all
    '
    exit
  fi

  detect_action
  
  case $action in

  "search") do_search
    ;;
  "install") do_install
    ;;
  "remove") do_remove
    ;;

  esac
}

function detect_action {
  arg=${args[0]}
  for action in $ACTIONS; do
    if [ $arg == $action ]; then
      break
    else
      action=''
    fi
  done

  if [ -z $action ]; then
    throw_error "Invalid action"
  fi
}

function make_request {
  url="$RPC_URL?type=$1&arg=$2"
  echo $url
  echo `curl $url`
  exit
}
 
function do_search {
  term=${args[1]}
  if [ -z $term ]; then
    throw_error 'Missing search term'
  fi

  make_request 'search' $term
}

function throw_error {
  echo "Error: $1"
  exit
}

function clean_up {
  # TODO: Stub, used for clean up
  exit
}

main $*

